@base_url = http://localhost:8080

POST {{base_url}}/api/auth/register
content-type: application/json
X-PrivateTenant: MRT

{
    "username": "sobhan",
    "password": "password",
    "role": "user"
}

###
# @name login

POST {{base_url}}/api/auth/login
content-type: application/json
X-PrivateTenant: MRT


{
    "username": "sobhan",
    "password": "password"
}


###
# @name createdIssue
POST {{base_url}}/api/issues
content-type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


{
    "title": "Booking is not working",
    "description": "Not Booked",
    "status": "NEW"
}

###
# @name createdIssue
POST {{base_url}}/api/issues
content-type: application/json
Authorization: Bearer {{login.response.body.accessToken}}


{
    "title": "Booking history is not displaying my old bookings",
    "description": "UI is blank when i try to see my old bookings",
    "status": "NEW"
}

###
PUT {{base_url}}/api/issues/9
content-type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
    "id": "9",
    "title": "Booking history is not displaying my old bookings",
    "description": "UI is blank when i try to see my old bookings",
    "status": "IN PROGRESS"
}

###

GET {{base_url}}/api/issues
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

